import { DeckSchema, type Deck, type DeckInput } from './schema.ts';

/**
 * Il mazzo di casa: domande e risposte vengono dai PDF stampabili del gruppo
 * (Domande, azioni, "nomi e cose"), importate con scripts/pdf-cards.py.
 */
const raw: DeckInput = {
  schemaVersion: 1,
  id: 'cirelli',
  name: 'Cards Against Cirelli',
  language: 'it',
  description: 'Il mazzo di casa Cirelli.',
  black: [
    { text: 'La mattina, Calabrese è solita lavarsi il culo con ___________' },
    { text: '_____ e _____ tutta la notte' },
    { text: 'Buon natale a te e pure a quello/a stronzo/a di _______' },
    { text: 'Durante una pippa penso sempre a ______' },
    { text: 'Ho preso un nuovo gatto. Carino! Come si chiama? ___________' },
    { text: 'Il 3 ottobre gli italiani scenderanno in piazza per protestare a favore d* ______' },
    { text: 'Nelle sue playlist non può mancare proprio _________' },
    { text: 'La mattina non possono mancare latte al cacao, cereali, caffè e ________' },
    { text: 'Questa tisana serve a ___________' },
    {
      text: 'Simo che fai oggi? “Mah guarda alle 15:00 ho una call, alle 17:00 devo _________ fino alle 21:00, poi ci sono”',
    },
    { text: 'Scrivere a c’è posta per te solo per _________ in diretta nazionale' },
    {
      text: 'Quando Alessandro ha letto le carte mi ha rivelato che domani dovrà ________________',
    },
    { text: 'Gabriel non fa mai mancare ____________ quando c’è Simone' },
    { text: 'Quando nient’altro funziona, posso sempre masturbarmi con ________' },
    { text: 'Questo mese su Donna Moderna: "Riaccendi il desiderio con ________ "' },
    {
      text: 'Un colloquio di lavoro di successo inizia con una solida stretta di mano e finisce con ________',
    },
    { text: 'Mi aiuti dottore, ho ________ dentro il culo!' },
    {
      text: 'Mi faccio il culo tutto il giorno per la mia famiglia, e quando torno a casa devo trovare ________!?',
    },
    { text: 'Simone Ciocca una volta ha portato un cosplay di _____' },
    { text: 'Girano voci che al Vaticano ci sia una stanza segreta per ________' },
    { text: 'Simone ha creato un’app per ____________ incredibile!' },
    { text: 'Caro Cioè, ho difficoltà con ________ e vorrei qualche consiglio' },
    { text: '___________ è il mio nuovo fetish' },
    { text: '________ : testato dai bambini, approvato dalle mamme' },
    { text: 'Da quando Cirelli si è fidanzato, Tocci ha iniziato a _________ senza di lui.' },
    { text: 'Un cono tre gusti per favore: cioccolato, limone e ______.' },
    {
      text: 'Durante la vacanza in Trentino, Falzarano ha diviso il letto con ________ che ha scorreggiato tutta la notte.',
    },
    { text: 'Il nuovo corso che si terrà al Cantiere dell’arte insegnerà ai bambini a _____.' },
    { text: 'Non diresti mai che Cesare in realtà è un ____________.' },
    { text: 'Il lavoro segreto di Gabriel Gambino è ________.' },
    { text: 'Sul palco del Priverno Comics, Cirelli si è divertito a ______.' },
    {
      text: 'Il nuovo video di Futuro Nazionale vede come protagonista _____ che _____ con dei migranti.',
    },
    { text: 'Giorgia Meloni ha girato un porno con ________.' },
    { text: 'Al prossimo nerd fest, l’ospite principale dovrà ________.' },
    { text: 'Il segreto per rimanere giovani è semplicemente _______.' },
    { text: 'La canna perfetta si rolla a bandiera, la sega perfetta si fa con ________.' },
    { text: 'Al Latina Comics non mancherà di certo ________.' },
    { text: '_______è la categoria porno preferita Valerio Montesarchio.' },
    { text: 'Come fanno Daniele e Francesca a stare insieme da più di 12 anni? _____' },
    {
      text: 'Giovanni quando si ferma al mcdonald’s prende sempre un mc menù large a base di _____, _____ e coca cola.',
    },
    { text: 'Claudia ha iniziato a insegnare teatro per __________.' },
    { text: 'Per me una pasta con tonno e _____.' },
    { text: 'Non sono razzista ma non sopporto proprio ______.' },
    { text: 'Quest’anno a condurre Sanremo ci sarà ______.' },
    { text: 'La nuova legge di Fratelli d’Italia legalizzerà ____ nelle scuole.' },
    { text: 'Per aprire il forziere devi recitare “Tisca, tusca, _______!”' },
    { text: 'Hanno trovato ________ nel portabagagli di Denise.' },
    { text: '_______ è il modo con cui Tocci corteggia una ragazza.' },
    { text: 'Cosa fa Alessandro Federici quando non scrocca? _______' },
    { text: 'Il vero motivo per cui Israele finanzia l’ai è per ________.' },
    { text: 'Ogni volta che siamo in saletta succede sempre che ________.' },
    { text: 'Sono un autolesionista, basta con _______, disse Totani.' },
    { text: 'Quando Daniele gira una canna, ma si parla di ______, smette di rollare.' },
    { text: 'Francesca Candeli non si arrabbia mai, ma quando si arrabbia potrebbe ____________.' },
    { text: 'Non siete più il mio ________.' },
    { text: 'Cantami o diva del _________.' },
    { text: 'L’ultima ricerca google di Simone Ciocca è stata _________.' },
    { text: 'La volante dei carabinieri ci ha chiesto ________ con gli auguri al festeggiato.' },
    { text: 'Sopra la panca la capra _______, sotto la panca _______ _______' },
    { text: 'Il nuovo programma della Lega prevede _____, _______, e tant* _______.' },
    { text: 'Qual è la tua/il tuo ________. Un nuovo libro firmato Fabio Mattocci.' },
    { text: 'Per torturare i civili palestinesi, l’IDF usano _____________.' },
    {
      text: 'Il prossimo spettacolo con la regia di Claudia Casale, si chiamerà ______. Interpretato da _________.',
    },
    { text: 'Alessandro Federici è risultato essere dipendente da ____________.' },
    {
      text: 'Benvenuti ad una nuova puntata di Chi L’ha Visto, oggi parliamo della scomparsa di _________.',
    },
    { text: 'Nel gioco della sigaretta spesso _______ e ______ capitano sempre insieme.' },
    { text: 'Mamma! Mamma! Guarda laggiù c’è ____________ che si diverte a ____________!' },
    { text: 'Il segreto della velocità di Usain Bolt sta nel __________.' },
    { text: '________ è il motivo per cui Astro è sempre in ritardo.' },
    { text: 'La telecamera di Mauro durante il campeggio ha ripreso _____ mentre ________.' },
    { text: 'Luca lo presti non saprà usare il pc ma sa benissimo come ________.' },
    { text: 'Il sogno proibito di Giovanni Contestabile è _________.' },
    { text: '__________ è la categoria porno preferita da Simone' },
    { text: 'Dopo essere svenuto al capodanno, Simone è stato svegliato da ________' },
    { text: 'Simone ha il sogno di duettare con __________' },
    { text: 'I soldi non compreranno l’amore, lui può sicuramente comprare ________' },
    { text: 'A Latina Fiori sta aprendo un negozio dove vendono ______' },
    {
      text: 'Mentre gli Stati Uniti bombardano l’Iran, Simone pensa che ci voglia _________ per salvare il mondo.',
    },
    { text: 'Al primo appuntamento è sempre buona educazione _______' },
    { text: 'La scienza non spiegherà mai l’origine di ________' },
    {
      text: 'Mia mamma è impazzita quando nella cronologia del mio browser ha visto ________ .com',
    },
    { text: 'Nel settimo girone infernale, i peccatori devono subire ________ per l’eternità' },
    { text: 'Nella prossima puntata di Rai Educational: Come parlare a tuo figlio di ________' },
    { text: 'Parla il capitano. Allacciate le cinture e preparatevi per ________' },
  ],
  white: [
    { text: 'Il lavandino sborrato da Valerio Montesarchio' },
    { text: 'Lasciare un messaggio imbarazzante in segreteria' },
    { text: 'Spogliarsi e mettersi a guardare l’Albero Azzurro' },
    { text: 'Fare l’occhiolino a persone anziane' },
    { text: 'Aprire un canale tiktok con gli edit simp per la Schlein' },
    { text: 'Essere un adulto senza soldi con molte cose importanti da fare' },
    {
      text: 'Acquistare tutti i biglietti del musical di Cirelli per rivenderli al doppio del prezzo',
    },
    { text: 'Mascherare una risata quando vengono menzionati i raduni a predappio' },
    { text: 'Ballare nudo la mazurka al matrimonio di uno sconosciuto' },
    { text: 'Chiedere il congedo mestruale' },
    {
      text: 'Fare incazzare Franca del sosò facendola diventare una bestia arcana di secondo livello',
    },
    { text: 'Proporsi come animatore alle case di riposo' },
    { text: 'Masturbarsi con un donut del mc cafè' },
    { text: 'Libero di Paola' },
    { text: 'Benjamin Netanyahu' },
    { text: 'Putin che cavalca un orso a petto nudo' },
    { text: 'Cagarsi addosso durante una scampagnata a Campoli' },
    { text: 'Silvio Berlusconi con un dito nel culo' },
    { text: 'Mauro D’Angiolillo' },
    { text: 'L’acquario di Alessandro Federici.' },
    {
      text: 'Scrivere sulle mattonelle dei bagni dell’autogrill nei pressi di Viareggio il numero di Michela Cecere',
    },
    { text: 'Fentanyl' },
    { text: 'Proporre una messicana di mezzanotte a parco san marco' },
    { text: 'Una serie netflix prodotta da Fabrizio Corona' },
    { text: 'Finire i biscotti per la vendita di beneficienza contro l’AIDS, prima che inizi' },
    { text: 'Fare sesso sopra una pizza' },
    { text: 'Fare sesso alla guida' },
    { text: 'Fare sesso nel bagno della Cisl' },
    { text: 'Fare sesso al cantiere dell’arte' },
    { text: 'Andare a fare una vacanza approfittando dell’assenza di Epstein sulla sua isola' },
    { text: 'Riscrivere gli Epstein files ma sostituendo Donald Trump con Iginio Massari' },
    { text: 'Cacare a piana delle orme nel mezzo del mercatino dell’elettronica' },
    { text: 'Farsi leggere i tarocchi da Alessandro Federici' },
    { text: 'Essere in mezzo a un gruppo di mimi che fingono di scoparti' },
    { text: 'Comporre una versione jazz di Faccetta Nera' },
    { text: 'Spiderman' },
    { text: 'Francesca Cannella' },
    { text: 'Vannacci' },
    { text: 'Il clown del McDonald ma con i colori israeliani' },
    { text: 'Andrea Bocelli' },
    { text: 'Pasta col tonno' },
    { text: 'Cannelloni, lasagne ed eiaculazione precoce' },
    { text: 'Alzabandiera mattutino' },
    { text: 'Mal di pancia e flautolenze' },
    { text: 'Caffè borbone' },
    { text: 'Gino Fastidio' },
    { text: 'I file desecretati della CIA' },
    { text: 'Scambiare Gabriella Califano per la madre carnale di Simone' },
    { text: 'Cagare in una villa abusiva sinti di Rocca Cencia' },
    { text: 'Essere venerati in quanto unico vero Dio' },
    { text: 'Brindare alla figa' },
    { text: 'Suonare tutti i citofoni di Via Legnano' },
    { text: 'Partecipare come spettatore ad una puntata di Amici di Maria de Filippi' },
    { text: 'Sputare sui bambini ciechi dicendo loro che piove' },
    { text: 'Toccare i capezzoli turgidi di Lorenzo Cirelli' },
    { text: 'Scorreggiare in un barattolo ermetico' },
    { text: 'Annusare i piedi di un maratoneta domenicale sulla via del mare' },
    { text: 'Andare a rompere nuovamente il dinosauro dei giardinetti tardandone la riapertura' },
    { text: 'Bucare su via Veio per colpa delle voragini' },
    { text: 'I patti lateranensi' },
    { text: 'Gorgheggi in momenti inappropriati' },
    { text: 'Diarrea mascherata da scorreggia' },
    { text: 'Massimo Giletti che inneggia alla destra' },
    { text: 'Il macellaio del Conad di via Ezio' },
    { text: 'Un liquidator pieno di maionese al tartufo Heinz' },
    { text: 'La sacra salma di Padre Pio' },
    { text: 'Il fallo sott’aceto di Rasputin' },
    { text: 'Una canzone degli ABBA' },
    { text: 'Il KKK' },
    { text: 'Una soap opera turca' },
    { text: 'Antonella Clerici che scopre cos’è la Borra' },
    { text: 'Amaro Gabriele' },
    { text: 'Aldo, Giovanni e Giacomo Camerano' },
    { text: 'Barbascura x' },
    { text: 'Frank Matano ma con la tourette' },
    { text: 'La sede CISL di Via Cairoli' },
    { text: 'Claudia Casale ma Pakistana' },
    { text: 'Un reel di Coez' },
    { text: 'Nu matrimonio napuletano' },
    { text: 'Mauro D’Angiolillo ma Veneto' },
    { text: 'Le foibe' },
    { text: 'Una spagnola fatta da una spagnola' },
    { text: 'Yà lì shān dé luó (Alessandro ma cinese)' },
    { text: 'Benito Mussolini' },
    { text: 'Un pokèmon di tipo culo' },
    { text: 'La faccia schiacciata di un carlino' },
    { text: 'La fatina del primo sborrino' },
    { text: 'Un masturbatore femminile a forma di Stegosauro' },
    { text: 'Mariangela Fantozzi' },
    { text: 'Un gruppo di lontre modificate geneticamente' },
    { text: 'L’agitazione prima di un esame prostatico' },
    { text: 'Un paio di manette di peluche, dell’olio Johnson’s baby e una playlist di P. Diddy' },
    { text: 'Gli outfit di Cristiano Malgioglio' },
    { text: 'Il one piece' },
    { text: 'Un cinese poco bravo in matematica' },
    { text: 'Fare battute fuori luogo sull’Olocausto' },
    { text: 'Far partire una diretta instagram durante una sega' },
    { text: 'Molestare Bruno Vespa a Montecitorio' },
    { text: 'Ascoltare l’intera discografia di Marco Masini' },
    { text: 'Usare un lubrificante alla carbonara' },
    { text: 'Fare acquisti su un sito di sex toys svedese' },
    { text: 'Grattarsi il culo e poi annusarsi le dita' },
    { text: 'Togliersi i pelucchi da dentro l’ombelico' },
    {
      text: 'Mettere un banchetto con i busti del duce al mercatino della prima domenica del mese',
    },
    { text: 'Attaccare nella propria autovettura un santino di Pacciani' },
    { text: 'Sostenere l’innocenza di Marco Limone' },
    { text: 'Fare beneficenza ai bambini in africa' },
    { text: 'Sniffare cocaina dal cazzo duro di un clown' },
    { text: 'Il complotto del Titanic' },
    { text: 'Sfaccimma' },
    { text: 'Piccioni grassi' },
    { text: 'Nani spacciatori di crack' },
    { text: 'Il cosplayer ufficiale di Donald Trump' },
    { text: 'Un segone a due mani' },
    { text: 'Una stretta di mano interrazziale' },
    { text: 'Un indiano Navajo che risolve crimini viaggiando nel mondo degli spiriti' },
    { text: "10 incredibili curiosità sull'ano" },
    { text: 'Una troupe di soli nani che rappresenta il Riccardo III di Shakespeare' },
    { text: 'Una trappola dei Viet Cong' },
    { text: 'Molestare minorenni fuori alla Gianni Rodari' },
    { text: 'Lavorare part time in cucina al sottoscala9' },
    { text: 'Essere tenuto in disparte durante un’orgia al sottoscala9' },
    { text: 'Fare il motoscafo tra le tette di Platinette' },
    { text: 'Mangiare 3kg di olive all’ascolana' },
    { text: 'Ruttare all’orecchio di un passante' },
    { text: 'Leccarsi le dita dopo aver pisciato' },
    { text: 'Chiudere Lorenzo Cirelli vestito da maggiordomo nella cella frigorifera' },
    { text: 'Chiamare Dario Rosati nel cuore della notte chiedendo che mutandine indossa' },
    { text: 'Perdere in una gara di rollaggio della canna con Daniele Siragusa' },
    { text: 'Imparare ad usare il pc in un corso avanzato con Luca Lo Presti' },
    { text: 'Accompagnare Viola a 223 concerti l’anno non potendone vedere nemmeno uno' },
    { text: 'Le puntate di Naruto scaricate sul portatile di Osama Bin Laden' },
    { text: 'Tettine sode' },
    { text: 'Una sorprendente quantità di capelli' },
    { text: 'Una presentazione PowerPoint' },
    { text: 'Una piccola manina rachitica' },
    { text: 'Il gas fornito dalla Russia' },
    { text: 'Una delicata carezza sull’interno coscia' },
    { text: 'Una cena a buffet di pesce a 3.99€' },
    { text: 'I piselli surgelati del Todis' },
    { text: 'Una multa per aver parcheggiato al posto per handicappati davanti Latina Fiori' },
    { text: 'Un’erezione che dura più di quattro ore' },
    { text: 'Un’insalata russa da asporto' },
    { text: 'Preservativi di Hello Kitty' },
    { text: 'Arcanissima Accademia' },
    { text: 'Acqua di Nepi' },
    { text: 'Le olive di Tocci' },
    { text: 'Enzo Miccio' },
    { text: 'Una tazza ufficiale del Duce presa su predappio store' },
    { text: 'Una expo dedicata all’agricoltura' },
    { text: 'La sagra del carciofo di Sezze' },
    { text: 'Il rosario recitato dall’anziana del piano di sopra' },
    { text: 'Il bagno di Montecitorio' },
    { text: 'Qualunque cosa usino per fare i Chicken McNuggets' },
    { text: 'Il pacifico e innocuo sviluppo della Cina' },
    { text: 'Scaccolarsi con l’alluce del piede sinistro' },
    { text: 'Avere peli pubici fra i denti' },
    { text: 'Pulire un water incrostato, in un autogrill nel napoletano' },
    {
      text: 'Aver paura dei vicoli bui mentre cammini per strada con addosso soltanto un impermeabile rosa',
    },
    { text: 'Organizzare cene eleganti per scopi professionali' },
    { text: 'Volere la botte piena, la moglie ubriaca e un cazzo in culo' },
    {
      text: 'Diabolico nell’amplesso, sproporzionato per quel che riguarda le dimensioni del sesso',
    },
    { text: 'Scorreggiare in un ascensore affollato e guardare schifato quello affianco' },
    { text: 'Fare i gargarismi con il cemento liquido a presa rapida' },
    { text: 'Fare piedino alla persona sbagliata' },
    { text: 'Annusare il culo ai passanti credendosi un cane' },
    { text: 'Mettere il dito nel culo di pikachu e prendere la scossa' },
    { text: 'Schiaffeggiare una vecchietta razzista' },
    { text: 'Scopare da dio' },
    { text: 'Scoreggiare e andarsene via' },
    { text: 'Sottomettersi sessualmente ad Elon Musk' },
    { text: 'Starnutire, scoreggiare, ed eiaculare nello stesso istante' },
    { text: 'Cacare sulla bandiera israeliana' },
    { text: 'Guarire gli omosessuali con la preghiera' },
    { text: 'Fare spesa al carrefour alle 2 del mattino' },
    { text: 'Svegliarsi bagnati e mezzi nudi nel parcheggio dell’IKEA' },
    { text: 'Chiedere le percentuali alle OnlyFanser della provincia di Latina' },
    { text: 'Frustare uno schiavo disobbediente' },
    { text: 'Fingere di essere interessati' },
    { text: 'Sborrare su un gruppo di suore africane che passeggiano per Roma' },
    { text: 'Pisciare nel lavello della cucina di Lorenzo Cirelli' },
    { text: 'Ubriacarsi con i cocktails del sosò' },
    { text: 'Mandare una foto dei piedi a Tony Pitony' },
    { text: 'Mandare una foto del cazzo (presa da internet)' },
    { text: 'Creare con l’AI una versione furry di Giorgia Meloni' },
    { text: 'Denudare i politici russi con l’intelligenza artificiale' },
    { text: 'Trainare un robot di Tesla per farsi fare le pippe' },
    { text: 'Cambiare gli avvisi di condominio del signor Delfino' },
    { text: 'Baciare una fotografia di Donald Trump prima di andare a dormire' },
    {
      text: 'Controllare compulsivamente le storie di Simone Ciocca per vedere se è stato circondato da figa anche oggi',
    },
    { text: 'Tingersi il pube a righe bianche e rosa' },
    { text: 'Infilarsi un ravanello nel culo' },
    { text: 'Apparire come guest star nel nuovo video di Gemmadelsud' },
    { text: 'Entrare in una chiesa urlando di essere l’Anticristo' },
    { text: 'Rubare le matite di ikea e mettersele nel culo' },
    { text: 'Realizzare che è finita la carta igenica quando ormai è troppo tardi' },
    { text: 'Pulirsi il culo con un assorbente' },
    { text: 'Guardare un porno in pubblico sull’iPad a tutto volume' },
    { text: 'Vendere organi umani a basso costo e con scarse garanzie igeniche' },
    { text: 'Pensare di stare per saltare su un bel tronco e finire in una merda di vacca' },
    { text: 'Sparare a Charlie Kirk' },
    { text: 'Vestirsi da Peter Griffin e dimenticarsi come ci si siede' },
  ],
};

export const CIRELLI_DECK: Deck = DeckSchema.parse(raw);
