import { DEMO_DECK } from './demo.ts';
import { DeckSchema, type Deck, type DeckInput } from './schema.ts';

/**
 * Il mazzo di casa: le carte bianche vengono dai PDF stampabili del gruppo
 * (azioni e "nomi e cose"), importate con scripts/pdf-cards.py.
 * Le nere sono provvisorie (quelle del mazzo base) finché non arrivano le domande originali.
 */
const raw: DeckInput = {
  schemaVersion: 1,
  id: 'cirelli',
  name: 'Cards Against Cirelli',
  language: 'it',
  description: 'Il mazzo di casa Cirelli.',
  black: DEMO_DECK.black.map(({ text }) => ({ text })),
  white: [
    { text: 'Il lavandino sborrato da Valerio Montesarchio' },
    { text: 'Lasciare un messaggio imbarazzante in segreteria' },
    { text: 'Spogliarsi e mettersi a guardare l’Albero Azzurro' },
    { text: 'Fare l’occhiolino a persone anziane' },
    { text: 'Aprire un canale tiktok con gli edit simp per la Schlein' },
    { text: 'Essere un adulto senza soldi con molte cose importanti da fare' },
    {
      text: 'Acquistare tutti i biglietti del musical di Cirelli per rivenderli al doppio del prezzo',
    },
    { text: 'Mascherare una risata quando vengono menzionati i raduni a predappio' },
    { text: 'Ballare nudo la mazurka al matrimonio di uno sconosciuto' },
    { text: 'Chiedere il congedo mestruale' },
    {
      text: 'Fare incazzare Franca del sosò facendola diventare una bestia arcana di secondo livello',
    },
    { text: 'Proporsi come animatore alle case di riposo' },
    { text: 'Finire i biscotti per la vendita di beneficienza contro l’AIDS, prima che inizi' },
    { text: 'Fare sesso sopra una pizza' },
    { text: 'Fare sesso alla guida' },
    { text: 'Fare sesso nel bagno della Cisl' },
    { text: 'Fare sesso al cantiere dell’arte' },
    { text: 'Andare a fare una vacanza approfittando dell’assenza di Epstein sulla sua isola' },
    { text: 'Riscrivere gli Epstein files ma sostituendo Donald Trump con Iginio Massari' },
    { text: 'Cacare a piana delle orme nel mezzo del mercatino dell’elettronica' },
    { text: 'Farsi leggere i tarocchi da Alessandro Federici' },
    { text: 'Essere in mezzo a un gruppo di mimi che fingono di scoparti' },
    { text: 'Comporre una versione jazz di Faccetta Nera' },
    { text: 'Scambiare Gabriella Califano per la madre carnale di Simone' },
    { text: 'Cagare in una villa abusiva sinti di Rocca Cencia' },
    { text: 'Essere venerati in quanto unico vero Dio' },
    { text: 'Brindare alla figa' },
    { text: 'Suonare tutti i citofoni di Via Legnano' },
    { text: 'Partecipare come spettatore ad una puntata di Amici di Maria de Filippi' },
    { text: 'Sputare sui bambini ciechi dicendo loro che piove' },
    { text: 'Toccare i capezzoli turgidi di Lorenzo Cirelli' },
    { text: 'Scorreggiare in un barattolo ermetico' },
    { text: 'Annusare i piedi di un maratoneta domenicale sulla via del mare' },
    { text: 'Andare a rompere nuovamente il dinosauro dei giardinetti tardandone la riapertura' },
    { text: 'Bucare su via Veio per colpa delle voragini' },
    { text: 'I patti lateranensi' },
    { text: 'Gorgheggi in momenti inappropriati' },
    { text: 'Diarrea mascherata da scorreggia' },
    { text: 'Massimo Giletti che inneggia alla destra' },
    { text: 'Il macellaio del Conad di via Ezio' },
    { text: 'Un liquidator pieno di maionese al tartufo Heinz' },
    { text: 'La sacra salma di Padre Pio' },
    { text: 'Il fallo sott’aceto di Rasputin' },
    { text: 'Una canzone degli ABBA' },
    { text: 'Il KKK' },
    { text: 'Una soap opera turca' },
    { text: 'Antonella Clerici che scopre cos’è la Borra' },
    { text: 'Amaro Gabriele' },
    { text: 'Aldo, Giovanni e Giacomo Camerano' },
    { text: 'Barbascura x' },
    { text: 'Frank Matano ma con la tourette' },
    { text: 'La sede CISL di Via Cairoli' },
    { text: 'Claudia Casale ma Pakistana' },
    { text: 'Un reel di Coez' },
    { text: 'Nu matrimonio napuletano' },
    { text: 'Mauro D’Angiolillo ma Veneto' },
    { text: 'Le foibe' },
    { text: 'Una spagnola fatta da una spagnola' },
    { text: 'Yà lì shān dé luó (Alessandro ma cinese)' },
    { text: 'Sniffare cocaina dal cazzo duro di un clown' },
    { text: 'Il complotto del Titanic' },
    { text: 'Sfaccimma' },
    { text: 'Piccioni grassi' },
    { text: 'Nani spacciatori di crack' },
    { text: 'Il cosplayer ufficiale di Donald Trump' },
    { text: 'Un segone a due mani' },
    { text: 'Una stretta di mano interrazziale' },
    { text: 'Un indiano Navajo che risolve crimini viaggiando nel mondo degli spiriti' },
    { text: "10 incredibili curiosità sull'ano" },
    { text: 'Una troupe di soli nani che rappresenta il Riccardo III di Shakespeare' },
    { text: 'Una trappola dei Viet Cong' },
    { text: 'Le puntate di Naruto scaricate sul portatile di Osama Bin Laden' },
    { text: 'Tettine sode' },
    { text: 'Una sorprendente quantità di capelli' },
    { text: 'Una presentazione PowerPoint' },
    { text: 'Una piccola manina rachitica' },
    { text: 'Il gas fornito dalla Russia' },
    { text: 'Una delicata carezza sull’interno coscia' },
    { text: 'Una cena a buffet di pesce a 3.99€' },
    { text: 'I piselli surgelati del Todis' },
    { text: 'Una multa per aver parcheggiato al posto per handicappati davanti Latina Fiori' },
    { text: 'Un’erezione che dura più di quattro ore' },
    { text: 'Un’insalata russa da asporto' },
    { text: 'Benito Mussolini' },
    { text: 'Un pokèmon di tipo culo' },
    { text: 'La faccia schiacciata di un carlino' },
    { text: 'La fatina del primo sborrino' },
    { text: 'Un masturbatore femminile a forma di Stegosauro' },
    { text: 'Mariangela Fantozzi' },
    { text: 'Un gruppo di lontre modificate geneticamente' },
    { text: 'L’agitazione prima di un esame prostatico' },
    { text: 'Un paio di manette di peluche, dell’olio Johnson’s baby e una playlist di P. Diddy' },
    { text: 'Gli outfit di Cristiano Malgioglio' },
    { text: 'Il one piece' },
    { text: 'Un cinese poco bravo in matematica' },
    { text: 'Preservativi di Hello Kitty' },
    { text: 'Arcanissima Accademia' },
    { text: 'Acqua di Nepi' },
    { text: 'Le olive di Tocci' },
    { text: 'Enzo Miccio' },
    { text: 'Una tazza ufficiale del Duce presa su predappio store' },
    { text: 'Una expo dedicata all’agricoltura' },
    { text: 'La sagra del carciofo di Sezze' },
    { text: 'Il rosario recitato dall’anziana del piano di sopra' },
    { text: 'Il bagno di Montecitorio' },
    { text: 'Qualunque cosa usino per fare i Chicken McNuggets' },
    { text: 'Il pacifico e innocuo sviluppo della Cina' },
    { text: 'Masturbarsi con un donut del mc cafè' },
    { text: 'Libero di Paola' },
    { text: 'Benjamin Netanyahu' },
    { text: 'Putin che cavalca un orso a petto nudo' },
    { text: 'Cagarsi addosso durante una scampagnata a Campoli' },
    { text: 'Silvio Berlusconi con un dito nel culo' },
    { text: 'Mauro D’Angiolillo' },
    { text: 'L’acquario di Alessandro Federici.' },
    {
      text: 'Scrivere sulle mattonelle dei bagni dell’autogrill nei pressi di Viareggio il numero di Michela Cecere',
    },
    { text: 'Fentanyl' },
    { text: 'Proporre una messicana di mezzanotte a parco san marco' },
    { text: 'Una serie netflix prodotta da Fabrizio Corona' },
    { text: 'Spiderman' },
    { text: 'Francesca Cannella' },
    { text: 'Vannacci' },
    { text: 'Il clown del McDonald ma con i colori israeliani' },
    { text: 'Andrea Bocelli' },
    { text: 'Pasta col tonno' },
    { text: 'Cannelloni, lasagne ed eiaculazione precoce' },
    { text: 'Alzabandiera mattutino' },
    { text: 'Mal di pancia e flautolenze' },
    { text: 'Caffè borbone' },
    { text: 'Gino Fastidio' },
    { text: 'I file desecretati della CIA' },
    { text: 'Scaccolarsi con l’alluce del piede sinistro' },
    { text: 'Avere peli pubici fra i denti' },
    { text: 'Pulire un water incrostato, in un autogrill nel napoletano' },
    {
      text: 'Aver paura dei vicoli bui mentre cammini per strada con addosso soltanto un impermeabile rosa',
    },
    { text: 'Organizzare cene eleganti per scopi professionali' },
    { text: 'Volere la botte piena, la moglie ubriaca e un cazzo in culo' },
    {
      text: 'Diabolico nell’amplesso, sproporzionato per quel che riguarda le dimensioni del sesso',
    },
    { text: 'Scorreggiare in un ascensore affollato e guardare schifato quello affianco' },
    { text: 'Fare i gargarismi con il cemento liquido a presa rapida' },
    { text: 'Fare piedino alla persona sbagliata' },
    { text: 'Annusare il culo ai passanti credendosi un cane' },
    { text: 'Mettere il dito nel culo di pikachu e prendere la scossa' },
    { text: 'Schiaffeggiare una vecchietta razzista' },
    { text: 'Scopare da dio' },
    { text: 'Scoreggiare e andarsene via' },
    { text: 'Sottomettersi sessualmente ad Elon Musk' },
    { text: 'Starnutire, scoreggiare, ed eiaculare nello stesso istante' },
    { text: 'Cacare sulla bandiera israeliana' },
    { text: 'Guarire gli omosessuali con la preghiera' },
    { text: 'Fare spesa al carrefour alle 2 del mattino' },
    { text: 'Svegliarsi bagnati e mezzi nudi nel parcheggio dell’IKEA' },
    { text: 'Chiedere le percentuali alle OnlyFanser della provincia di Latina' },
    { text: 'Frustare uno schiavo disobbediente' },
    { text: 'Fingere di essere interessati' },
    { text: 'Molestare minorenni fuori alla Gianni Rodari' },
    { text: 'Lavorare part time in cucina al sottoscala9' },
    { text: 'Essere tenuto in disparte durante un’orgia al sottoscala9' },
    { text: 'Fare il motoscafo tra le tette di Platinette' },
    { text: 'Mangiare 3kg di olive all’ascolana' },
    { text: 'Ruttare all’orecchio di un passante' },
    { text: 'Leccarsi le dita dopo aver pisciato' },
    { text: 'Chiudere Lorenzo Cirelli vestito da maggiordomo nella cella frigorifera' },
    { text: 'Chiamare Dario Rosati nel cuore della notte chiedendo che mutandine indossa' },
    { text: 'Perdere in una gara di rollaggio della canna con Daniele Siragusa' },
    { text: 'Imparare ad usare il pc in un corso avanzato con Luca Lo Presti' },
    { text: 'Accompagnare Viola a 223 concerti l’anno non potendone vedere nemmeno uno' },
    { text: 'Fare battute fuori luogo sull’Olocausto' },
    { text: 'Far partire una diretta instagram durante una sega' },
    { text: 'Molestare Bruno Vespa a Montecitorio' },
    { text: 'Ascoltare l’intera discografia di Marco Masini' },
    { text: 'Usare un lubrificante alla carbonara' },
    { text: 'Fare acquisti su un sito di sex toys svedese' },
    { text: 'Grattarsi il culo e poi annusarsi le dita' },
    { text: 'Togliersi i pelucchi da dentro l’ombelico' },
    {
      text: 'Mettere un banchetto con i busti del duce al mercatino della prima domenica del mese',
    },
    { text: 'Attaccare nella propria autovettura un santino di Pacciani' },
    { text: 'Sostenere l’innocenza di Marco Limone' },
    { text: 'Fare beneficenza ai bambini in africa' },
    { text: 'Tingersi il pube a righe bianche e rosa' },
    { text: 'Infilarsi un ravanello nel culo' },
    { text: 'Apparire come guest star nel nuovo video di Gemmadelsud' },
    { text: 'Entrare in una chiesa urlando di essere l’Anticristo' },
    { text: 'Rubare le matite di ikea e mettersele nel culo' },
    { text: 'Realizzare che è finita la carta igenica quando ormai è troppo tardi' },
    { text: 'Pulirsi il culo con un assorbente' },
    { text: 'Guardare un porno in pubblico sull’iPad a tutto volume' },
    { text: 'Vendere organi umani a basso costo e con scarse garanzie igeniche' },
    { text: 'Pensare di stare per saltare su un bel tronco e finire in una merda di vacca' },
    { text: 'Sparare a Charlie Kirk' },
    { text: 'Vestirsi da Peter Griffin e dimenticarsi come ci si siede' },
  ],
};

export const CIRELLI_DECK: Deck = DeckSchema.parse(raw);
