import { DeckSchema, type Deck, type DeckInput } from './schema.ts';

/** Mazzo demo: testi originali, scritti per questo gioco. */
const raw: DeckInput = {
  schemaVersion: 1,
  id: 'demo',
  name: 'Il mazzo della casa',
  language: 'it',
  description: 'Trenta nere e cento bianche per cominciare subito.',
  black: [
    { text: 'Il mio terapeuta dice che il problema non sono io, ma ___.' },
    { text: 'Alla riunione di condominio è stato messo ai voti ___.' },
    { text: 'Nonna, dopo il terzo bicchiere: «Ai miei tempi c’era ___.»' },
    { text: 'Che cosa c’è davvero nel ragù della zia?' },
    { text: 'Il nuovo slogan della Regione: ___. Vieni a trovarci.' },
    { text: 'Ho lasciato il lavoro per dedicarmi a tempo pieno a ___.' },
    { text: '___: il motivo per cui non mi invitano più ai matrimoni.' },
    { text: 'Il parroco ha interrotto la messa per colpa di ___.' },
    { text: 'Online ho venduto ___ e con i soldi ho comprato ___.' },
    { text: 'Il segreto di un matrimonio felice? ___.' },
    { text: 'Prossimamente in streaming: ___, la serie in otto puntate.' },
    { text: 'Che cosa tengo nel cassetto del comodino?' },
    { text: 'L’oroscopo di oggi: Mercurio è retrogrado, evita ___.' },
    { text: 'In gita scolastica la prof ha sequestrato ___.' },
    { text: 'La mia prima volta è stata rovinata da ___.' },
    { text: 'Per la cena aziendale il capo ha organizzato ___.' },
    { text: '___ più ___: la ricetta della mia adolescenza.' },
    { text: 'Che cosa ha trovato il medico durante la visita di controllo?' },
    { text: 'Con il nuovo decreto è severamente vietato ___.' },
    { text: 'Il gruppo delle mamme della 3B è esploso per ___.' },
    { text: 'Mio cugino ha aperto una startup che unisce ___ e ___.' },
    { text: 'Il vero motivo per cui ho cambiato palestra: ___.' },
    { text: 'Stasera al bar si discute animatamente di ___.' },
    { text: 'Che cosa non bisogna mai dire a una suocera?' },
    { text: 'Quest’anno il festival della canzone lo ha vinto ___.' },
    { text: 'Il navigatore mi ha portato dritto dritto in ___.' },
    { text: '___, ___ e ___: il mio weekend in tre parole.' },
    { text: 'Il santo patrono del paese ha fatto il miracolo: ___.' },
    { text: 'Il mio ultimo appuntamento al buio è finito con ___.' },
    { text: 'Stasera in prima serata, un documentario sulla vita segreta di ___.' },
  ],
  white: [
    { text: 'il gruppo WhatsApp del condominio' },
    { text: 'mia zia che commenta tutto su Facebook' },
    { text: 'la riunione che poteva essere una mail' },
    { text: 'un risotto scotto servito con orgoglio' },
    { text: 'il mio ex in pigiama al supermercato' },
    { text: 'le bollette della luce' },
    { text: 'un piccione con un passato oscuro' },
    { text: 'un vocale di undici minuti' },
    { text: 'la suocera in vivavoce' },
    { text: 'un tatuaggio tribale fatto in vacanza nel 2006' },
    { text: 'il cugino che vende integratori' },
    { text: 'l’ansia della domenica sera' },
    { text: 'un apericena senza cena' },
    { text: 'la nonna che ti mette il cappotto ad agosto' },
    { text: 'il parcheggio in doppia fila come stile di vita' },
    { text: 'il parroco che fa le dirette' },
    { text: 'un influencer in crisi mistica' },
    { text: 'un divano che ha visto troppe cose' },
    { text: 'gli spaghetti spezzati a metà' },
    { text: 'l’ananas sulla pizza' },
    { text: 'il cartello «torno subito» appeso da tre settimane' },
    { text: 'un mutuo trentennale' },
    { text: 'il commercialista che ti dà del tu' },
    { text: 'una gastrite con un brutto carattere' },
    { text: 'la playlist triste del 2009' },
    { text: 'il karaoke dopo il quarto spritz' },
    { text: 'un fidanzato di nome Brando' },
    { text: 'una zanzara alle tre di notte' },
    { text: 'la dichiarazione dei redditi' },
    { text: 'il silenzio dopo una battuta sbagliata' },
    { text: 'tua madre su LinkedIn' },
    { text: 'le slide con le transizioni a stelline' },
    { text: 'il pigiama di flanella del liceo' },
    { text: 'un criceto con ambizioni politiche' },
    { text: 'il piedino sotto il tavolo sbagliato' },
    { text: 'la dieta che inizia lunedì' },
    { text: 'un selfie con il santo patrono' },
    { text: 'il vicino che usa il trapano la domenica mattina' },
    { text: 'un’eredità fatta solo di debiti' },
    { text: 'il fantasma dell’ex coinquilino' },
    { text: 'la lavatrice che balla la tarantella' },
    { text: 'un gratta e vinci da due euro' },
    { text: 'una Panda del ’98 con un’anima' },
    { text: 'l’abbonamento in palestra mai usato' },
    { text: 'il sacchetto pieno di sacchetti' },
    { text: 'un modulo compilato a penna rossa' },
    { text: 'il colloquio di lavoro in videochiamata, in mutande' },
    { text: 'lo zio che parla di politica al cenone' },
    { text: 'il buco nel calzino proprio quel giorno' },
    { text: 'un messaggio che dice «dobbiamo parlare»' },
    { text: 'l’ultima fetta di pizza' },
    { text: 'il bidet spiegato a un turista' },
    { text: 'un amore estivo in Riviera' },
    { text: 'la carbonara con la panna' },
    { text: 'un gatto che ti giudica' },
    { text: 'la prof di matematica in discoteca' },
    { text: 'la crisi dei trent’anni' },
    { text: 'un ottantenne che balla nei video' },
    { text: 'il prosecco caldo' },
    { text: 'la sagra della porchetta' },
    { text: 'il gruppo del calcetto del giovedì' },
    { text: 'il reggiseno che si slaccia in chiesa' },
    { text: 'un esame del sangue imbarazzante' },
    { text: 'un corso online su come piangere con dignità' },
    { text: 'la marmellata della nonna, scaduta nel 2011' },
    { text: 'il coinquilino che non compra mai la carta igienica' },
    { text: 'un ex che si rifà vivo ogni novembre' },
    { text: 'una multa per eccesso di entusiasmo' },
    { text: 'la tombola con premi discutibili' },
    { text: 'il pandoro senza zucchero a velo' },
    { text: 'la mamma che ti chiama col nome del cane' },
    { text: 'un mojito con troppa menta' },
    { text: 'il wifi del treno regionale' },
    { text: 'il sorriso del dentista quando prepara il conto' },
    { text: 'un’ascella sudata in metropolitana' },
    { text: 'la cena di classe dopo vent’anni' },
    { text: 'l’inflazione emotiva' },
    { text: 'la vicina che sa tutto di tutti' },
    { text: 'un ragazzo con la chitarra a una festa' },
    { text: 'il rutto libero come forma d’arte' },
    { text: 'le infradito con i calzini' },
    { text: 'la pizza al taglio alle quattro del mattino' },
    { text: 'il curriculum con la foto in costume' },
    { text: 'un pupazzo di neve con intenzioni sospette' },
    { text: 'la mia playlist per le serate romantiche' },
    { text: 'un caffè lungo ordinato a Napoli' },
    { text: 'l’astrologa di fiducia' },
    { text: 'la richiesta d’amicizia del capo' },
    { text: 'un trolley che non vuole andare dritto' },
    { text: 'il pranzo di Pasqua che dura sei ore' },
    { text: 'un vassoio di tortellini conteso in tribunale' },
    { text: 'un nudo artistico al museo civico' },
    { text: 'la crisi di mezza età di papà' },
    { text: 'una canzone di Natale a ottobre' },
    { text: 'lo sconto del cinque per cento sulla dignità' },
    { text: 'un drone che consegna rimpianti' },
    { text: 'il dito nella marmellata' },
    { text: 'il parroco in moto' },
    { text: 'il silenzio offeso della mamma dopo pranzo' },
    { text: 'la pasta «al dente» secondo uno zio di Milano' },
  ],
};

export const DEMO_DECK: Deck = DeckSchema.parse(raw);
